<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE data [
  <!ELEMENT data       (parameter+)>
  <!ELEMENT parameter  (name,value)>
  <!ELEMENT name       (#PCDATA)>
  <!ELEMENT value      (#PCDATA)>
]>
<data>
	<parameter>
		<name>DB_L2174_ALARMS</name>
		<value><![CDATA[000000000000000000000000000000000]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_LICENCE_OPTIONS</name>
		<value><![CDATA[1111101111101111000000000100000000000000]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_RX_MODE</name>
		<value><![CDATA[LMST(S)]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_FREQ1</name>
		<value><![CDATA[2.285000]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_MOD_TYPE</name>
		<value><![CDATA[16QAM]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_CHAN_BW</name>
		<value><![CDATA[10MHz]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_GUARD_INT</name>
		<value><![CDATA[Auto]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_SPEC_POL</name>
		<value><![CDATA[Normal]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_FEC_RATE</name>
		<value><![CDATA[2/3]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_PRE_BER</name>
		<value><![CDATA[1267]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_POST_BER</name>
		<value><![CDATA[0]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_TPS_LOCK</name>
		<value><![CDATA[Locked]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_FEC_LOCK</name>
		<value><![CDATA[Locked]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_PKT_ERR_RATE</name>
		<value><![CDATA[0]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_RX_MODE</name>
		<value><![CDATA[LMST(S)]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_SOURCE_ID</name>
		<value><![CDATA[03a96347]]></value>
	</parameter>
	<parameter>
		<name>DB_ETRAX_SOURCE_ID</name>
		<value><![CDATA[0112e6eb]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_SPEC_POL</name>
		<value><![CDATA[Normal]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_ASI1_OUTPUT_MUX</name>
		<value><![CDATA[Diversity]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_ASI2_OUTPUT_MUX</name>
		<value><![CDATA[Demod]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_VIDEO_OUTPUT_MUX</name>
		<value><![CDATA[Demod out 1]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_ASI_OUTPUT_MUX</name>
		<value><![CDATA[Demod out 2]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_IP1_OUTPUT_MUX</name>
		<value><![CDATA[Off]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_DOWN_CONVERTER_1</name>
		<value><![CDATA[3025-1927E]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_LNB_PWR_1</name>
		<value><![CDATA[Off]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_LNB_PWR_2</name>
		<value><![CDATA[Off]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_LNB_PWR_3</name>
		<value><![CDATA[Off]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_LNB_PWR_4</name>
		<value><![CDATA[Off]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_PWR_LEVEL_1</name>
		<value><![CDATA[-74.3]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_PWR_LEVEL_2</name>
		<value><![CDATA[-79.3]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_PWR_LEVEL_3</name>
		<value><![CDATA[-84.5]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_PWR_LEVEL_4</name>
		<value><![CDATA[-87.5]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_MER_1</name>
		<value><![CDATA[15.4]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_MER_2</name>
		<value><![CDATA[15.1]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_MER_3</name>
		<value><![CDATA[12.8]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_MER_4</name>
		<value><![CDATA[5.8]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_COARSE_LOCK_1</name>
		<value><![CDATA[Locked]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_COARSE_LOCK_2</name>
		<value><![CDATA[Locked]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_COARSE_LOCK_3</name>
		<value><![CDATA[Locked]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_COARSE_LOCK_4</name>
		<value><![CDATA[Locked]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_DATA_ENABLE</name>
		<value><![CDATA[Off]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_DATA_BAUD</name>
		<value><![CDATA[1200]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_DATA_PARITY</name>
		<value><![CDATA[Odd]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUTO_SERVICE</name>
		<value><![CDATA[On]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_NUM_SERVICES</name>
		<value><![CDATA[01]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_SERVICE_NAME</name>
		<value><![CDATA[Service 01]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_SERVICE_NAME_LIST</name>
		<value><![CDATA[Service One]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_PCR_LOCK</name>
		<value><![CDATA[No Lock]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_GEN_LOCK_ERROR</name>
		<value><![CDATA[OK]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_NETWORK_NAME</name>
		<value><![CDATA[]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CHROMA</name>
		<value><![CDATA[4:2:0]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_FREEZE_ON_LOSS</name>
		<value><![CDATA[Freeze]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_PSF_MODE</name>
		<value><![CDATA[Off]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_VIDEO_INPUT_MODE</name>
		<value><![CDATA[H264]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_LINE_STD</name>
		<value><![CDATA[1080I/50]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_VIDEO_A_TYPE</name>
		<value><![CDATA[SDI]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_VIDEO_B_TYPE</name>
		<value><![CDATA[SDI]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_MPEG1_AUDIO_A_BITRATE</name>
		<value><![CDATA[384Kbs]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_A_PID</name>
		<value><![CDATA[0257]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_B_PID</name>
		<value><![CDATA[1020]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_C_PID</name>
		<value><![CDATA[1010]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_D_PID</name>
		<value><![CDATA[1020]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_VIDEO_PID</name>
		<value><![CDATA[0256]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_PCR_PID</name>
		<value><![CDATA[0080]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_PROGRAM_ID</name>
		<value><![CDATA[0002]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_DATA_PID</name>
		<value><![CDATA[8190]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CCU_PID</name>
		<value><![CDATA[0044]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_AB_DID</name>
		<value><![CDATA[Group 1]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_CD_DID</name>
		<value><![CDATA[Group 2]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_SET_DEFAULT</name>
		<value><![CDATA[Off]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_COMMAND</name>
		<value><![CDATA[None]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_SCRAMBLING_TYPE</name>
		<value><![CDATA[Off]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_BISS_E_ID</name>
		<value><![CDATA[**************]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_VIDEO_FORMAT</name>
		<value><![CDATA[HD 1080i/50]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_LINE_OFFSET</name>
		<value><![CDATA[02960]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_NTSC_PED</name>
		<value><![CDATA[Pedestal]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_VIDEO_LOCKED</name>
		<value><![CDATA[Locked]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_POWER_FORMAT</name>
		<value><![CDATA[1080I/50]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_GEN_LOCK</name>
		<value><![CDATA[SD]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_OVERLAY_TYPE</name>
		<value><![CDATA[Basic]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_OVERLAY_BACKGROUND</name>
		<value><![CDATA[100]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_OVERLAY_ENABLE</name>
		<value><![CDATA[White]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_TYPE</name>
		<value><![CDATA[H264]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_BIT_DEPTH</name>
		<value><![CDATA[8]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_PICTURE_WIDTH</name>
		<value><![CDATA[1920]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_PICTURE_HEIGHT</name>
		<value><![CDATA[1088]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_STREAM_TYPE</name>
		<value><![CDATA[H264]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_IP2_OUTPUT_MUX</name>
		<value><![CDATA[Off]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_ASI2_OUTPUT_MUX</name>
		<value><![CDATA[---]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_PRESET_NUM</name>
		<value><![CDATA[001]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_PRESET_RECALL</name>
		<value><![CDATA[No]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_PRESET_STORE</name>
		<value><![CDATA[No]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_RUN_HOURS</name>
		<value><![CDATA[001848]]></value>
	</parameter>
	<parameter>
		<name>DB_ETRAX_PCB_TEMP</name>
		<value><![CDATA[43.9]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_WEB_TEXT</name>
		<value><![CDATA[L2174 RECEIVER]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_FPGA_TEMP</name>
		<value><![CDATA[79]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_BUILD_VERSION</name>
		<value><![CDATA[V0002]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_SERIAL_NUM</name>
		<value><![CDATA[0400436]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_SW_VERSION</name>
		<value><![CDATA[4.01]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_KERN_VERSION</name>
		<value><![CDATA[2.02]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_FPGA</name>
		<value><![CDATA[1.15]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_PCB</name>
		<value><![CDATA[4]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_ASI_1_LOCK</name>
		<value><![CDATA[No Lock]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_VOIP_ADDRESS</name>
		<value><![CDATA[192.168.000.122]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_IP_SUBNET</name>
		<value><![CDATA[255.255.255.000]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_IP_GATEWAY</name>
		<value><![CDATA[192.168.000.001]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_MAC_ADDRESS</name>
		<value><![CDATA[00:1D:65:49:63:47]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_PHY_SELECT</name>
		<value><![CDATA[Off Board]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_LINK_STATUS</name>
		<value><![CDATA[Link Down]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_LINK_SPEED</name>
		<value><![CDATA[10M HalfDuplex]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_IP1_LOCK</name>
		<value><![CDATA[No Lock]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_IP2_LOCK</name>
		<value><![CDATA[No Lock]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_IP3_LOCK</name>
		<value><![CDATA[No Lock]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_IP4_LOCK</name>
		<value><![CDATA[No Lock]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH1_DEST_ADDR</name>
		<value><![CDATA[192.168.000.095]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH1_DEST_PORT</name>
		<value><![CDATA[1000]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH1_SRC_PORT</name>
		<value><![CDATA[3000]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH1_NO_FEC</name>
		<value><![CDATA[Enable]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH1_TS_IP_TTL</name>
		<value><![CDATA[064]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH1_TS_IP_FEC_D</name>
		<value><![CDATA[05]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH1_TS_IP_FEC_L</name>
		<value><![CDATA[05]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH1_TS_IP_ENCAP_TYPE</name>
		<value><![CDATA[UDP only]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH1_TS_PER_IP</name>
		<value><![CDATA[7]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH1_RX_PORT</name>
		<value><![CDATA[1000]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH1_IP_TS_FEC_D</name>
		<value><![CDATA[07]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH1_IP_TS_FEC_L</name>
		<value><![CDATA[07]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH1_IP_TS_ENCAP_TYPE</name>
		<value><![CDATA[UDP only]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH1_IP_PER_TS</name>
		<value><![CDATA[0]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH1_IP_TS_DELAY</name>
		<value><![CDATA[8192]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH1_MULTICAST_ADDR</name>
		<value><![CDATA[230.168.000.095]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH1_MULTICAST_EN</name>
		<value><![CDATA[Enable]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH2_DEST_ADDR</name>
		<value><![CDATA[192.168.000.095]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH2_DEST_PORT</name>
		<value><![CDATA[2000]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH2_SRC_PORT</name>
		<value><![CDATA[4000]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH2_NO_FEC</name>
		<value><![CDATA[Enable]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH2_TS_IP_TTL</name>
		<value><![CDATA[000]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH2_TS_IP_FEC_D</name>
		<value><![CDATA[05]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH2_TS_IP_FEC_L</name>
		<value><![CDATA[05]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH2_TS_IP_ENCAP_TYPE</name>
		<value><![CDATA[UDP only]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH2_TS_PER_IP</name>
		<value><![CDATA[7]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH2_RX_PORT</name>
		<value><![CDATA[2000]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH2_IP_TS_FEC_D</name>
		<value><![CDATA[05]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH2_IP_TS_FEC_L</name>
		<value><![CDATA[05]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH2_IP_TS_ENCAP_TYPE</name>
		<value><![CDATA[UDP only]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH2_IP_PER_TS</name>
		<value><![CDATA[7]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH2_IP_TS_DELAY</name>
		<value><![CDATA[0000]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH2_MULTICAST_ADDR</name>
		<value><![CDATA[230.168.000.095]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_CH2_MULTICAST_EN</name>
		<value><![CDATA[Enable]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_A_TYPE</name>
		<value><![CDATA[Analogue]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_A_STANDARD</name>
		<value><![CDATA[MPEG L1]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_A_MODE</name>
		<value><![CDATA[Stereo]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_A_LOCKED</name>
		<value><![CDATA[Locked]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_A_SAMPLERATE</name>
		<value><![CDATA[48.0KHz]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_B_TYPE</name>
		<value><![CDATA[Analogue]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_B_STANDARD</name>
		<value><![CDATA[Off]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_B_LOCKED</name>
		<value><![CDATA[No Lock]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_C_TYPE</name>
		<value><![CDATA[Analogue]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_C_STANDARD</name>
		<value><![CDATA[Off]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_C_LOCKED</name>
		<value><![CDATA[No Lock]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_D_TYPE</name>
		<value><![CDATA[Analogue]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_D_STANDARD</name>
		<value><![CDATA[Off]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_AUDIO_D_LOCKED</name>
		<value><![CDATA[No Lock]]></value>
	</parameter>
	<parameter>
		<name>DB_CCU_STATUS</name>
		<value><![CDATA[Not Detected]]></value>
	</parameter>
	<parameter>
		<name>DB_STATUS_PIN_MODE</name>
		<value><![CDATA[Alarm]]></value>
	</parameter>
	<parameter>
		<name>DB_STATUS_PIN_ALARM_LEVEL</name>
		<value><![CDATA[High]]></value>
	</parameter>
	<parameter>
		<name>DB_DISPLAY_DECOD_LICENCE</name>
		<value><![CDATA[0203A96347DFF70002F000000000]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_CAM_BATT_VOLT</name>
		<value><![CDATA[0.0]]></value>
	</parameter>
	<parameter>
		<name>DB_DECODER_DISPLAY_BUILD</name>
		<value><![CDATA[1.31]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_DISPLAY_BUILD</name>
		<value><![CDATA[000.044]]></value>
	</parameter>
	<parameter>
		<name>DB_RESTORE_DEFAULTS</name>
		<value><![CDATA[No]]></value>
	</parameter>
	<parameter>
		<name>DB_DECOD_ASI_LOCK</name>
		<value><![CDATA[Locked]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_HW_OPTION_LCD</name>
		<value><![CDATA[MK 2 (white)]]></value>
	</parameter>
	<parameter>
		<name>DB_IP_ADDRESS</name>
		<value><![CDATA[010.000.101.110]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_ALLOW_WEB_UPGRADE</name>
		<value><![CDATA[No]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_PRESET_PROGRESS</name>
		<value><![CDATA[100]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_PROC_TYPE</name>
		<value><![CDATA[IMX27]]></value>
	</parameter>
	<parameter>
		<name>DB_L2174_REBOOT</name>
		<value><![CDATA[No]]></value>
	</parameter>
	<parameter>
		<name>DB_KEYPRESS</name>
		<value><![CDATA[0]]></value>
	</parameter>
	<parameter>
		<name>DB_FULL_LICENCE_ENTRY</name>
		<value><![CDATA[0000000000000000000000000000]]></value>
	</parameter>
	<parameter>
		<name>DB_UNIT_ESN</name>
		<value><![CDATA[00000060318E]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_UNIT_LICENCE_STATE</name>
		<value><![CDATA[Accepted]]></value>
	</parameter>
	<parameter>
		<name>DB_4INPUT_DEMOD_HARDWARE_STATE</name>
		<value><![CDATA[Enabled]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_FULL_LICENCE_ENTRY</name>
		<value><![CDATA[7372787F7F7F7F7F7F7F7FBC0333]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_CURRENT_1</name>
		<value><![CDATA[10]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_CURRENT_2</name>
		<value><![CDATA[12]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_CURRENT_3</name>
		<value><![CDATA[17]]></value>
	</parameter>
	<parameter>
		<name>DB_DEMOD_CURRENT_4</name>
		<value><![CDATA[11]]></value>
	</parameter>
	<parameter>
		<name>DB_P17101_DEBUG_PORT</name>
		<value><![CDATA[User data]]></value>
	</parameter>
	<parameter>
		<name>DB_P17101_SQUELCH</name>
		<value><![CDATA[Off]]></value>
	</parameter>
	<parameter>
		<name>DB_P17101_DIVERSITY_BITRATE</name>
		<value><![CDATA[40]]></value>
	</parameter>
	<parameter>
		<name>DB_DIVERSITY_HARDWARE_STATE</name>
		<value><![CDATA[Enabled]]></value>
	</parameter>
</data>
