<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE data [
  <!ELEMENT data	(parameter+)>
  <!ELEMENT parameter	(name, display*, units?, command?, min?, low?, mid?, up?, max?, option*)>
  <!ELEMENT command	(#PCDATA)>
  <!ELEMENT name       (#PCDATA)>
  <!ELEMENT display    (#PCDATA)>
  <!ELEMENT units      (#PCDATA)>
  <!ELEMENT option     (#PCDATA)>
  <!ELEMENT min        (#PCDATA)>
  <!ELEMENT low        (#PCDATA)>
  <!ELEMENT mid        (#PCDATA)>
  <!ELEMENT up         (#PCDATA)>
  <!ELEMENT max        (#PCDATA)>
  <!ATTLIST units   	type     CDATA #IMPLIED>
  <!ATTLIST option  	enabled  CDATA #IMPLIED>
	<!ATTLIST parameter  visible  CDATA #IMPLIED>
  <!ATTLIST display    index    CDATA #IMPLIED>
]>
<data>
	<parameter visible="yes">
		<name>DB_L2174_ALARMS</name>
		<display index="0">Clock fault </display>
		<display index="1">High Temperature</display>
		<display index="2">Demod High Temp</display>
		<display index="3">Decoder High Temp</display>
		<display index="4">Demod Comms Fault</display>
		<display index="5">Decoder Comms Fault</display>
		<display index="6">Synth not Locked</display>
		<display index="7">LPF not Tuned</display>
		<display index="8">ADC Clock not Locked</display>
		<display index="9">ASI Clock not Locked</display>
		<display index="10">LNB Fault</display>
		<display index="11">Invalid Frequency</display>
		<display index="12">Demod Freq Error</display>
		<display index="13">RF not Locked</display>
		<display index="14">TPS not Locked</display>
		<display index="15">FEC not Locked</display>
		<display index="16">ASI not Locked</display>
		<display index="17">Video not Locked</display>
		<display index="18">Audio 1 not Locked</display>
		<display index="19">Audio 2 not Locked</display>
		<display index="20">Frame not Locked</display>
		<display index="21">IP Link Error</display>
		<display index="22">IP not Locked</display>
		<display index="23">Test fault</display>
		<display index="24">Dummy</display>
		<display index="25">Fan1 fault</display>
		<display index="26">Fan2 fault</display>
		<display index="27">Lic format mismatch</display>
		<display index="28">Lic ID checksum error</display>
		<display index="29">Lic unit mismatch</display>
		<display index="30">Lic type mismatch</display>
		<display index="31">Channel 1,2 cal fail</display>
		<display index="32">Channel 3,4 cal fail</display>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_LICENCE_OPTIONS</name>
		<display index="0">SD MPEG-2 Low Delay</display>
		<display index="1">HD MPEG-2 Low Delay</display>
		<display index="2">MPEG-2 422</display>
		<display index="3">SD MPEG-2 Compliant</display>
		<display index="4">HD MPEG-2 Compliant</display>
		<display index="5">Licence Unused</display>
		<display index="6">SD H264 Main Profile</display>
		<display index="7">HD H264 Main Profile</display>
		<display index="8">H264 High Profile</display>
		<display index="9">H264 422</display>
		<display index="10">H264 10-Bit</display>
		<display index="11">Licence Unused</display>
		<display index="12">SD SDI Out</display>
		<display index="13">Dolby E Passthrough</display>
		<display index="14">Digital Audio</display>
		<display index="15">Audio Channels C/D</display>
		<display index="16">Licence Unused</display>
		<display index="17">Licence Unused</display>
		<display index="18">EBS</display>
		<display index="19">BISS</display>
		<display index="20">AES 128</display>
		<display index="21">AES 256</display>
		<display index="22">BCrypt 128</display>
		<display index="23">BCrypt 256</display>
		<display index="24">Licence Unused</display>
		<display index="25">IP Input</display>
		<display index="26">IP Output</display>
		<display index="27">Licence Unused</display>
		<display index="28">Remux</display>
		<display index="29">Packet Diversity</display>
		<display index="30">Dual Diversity</display>
		<display index="31">Status Overlay</display>
		<display index="32">Licence Unused</display>
		<display index="33">Licence Unused</display>
		<display index="34">Licence Unused</display>
		<display index="35">Licence Unused</display>
		<display index="36">Licence Unused</display>
		<display index="37">Licence Unused</display>
		<display index="38">Licence Unused</display>
		<display index="39">Licence Unused</display>
	</parameter>
	<parameter visible="yes">
		<name>DB_L2174_RX_MODE</name>
		<display><![CDATA[Mode]]></display>
		<option enabled="no"><![CDATA[None]]></option>
		<option enabled="yes"><![CDATA[DVBT]]></option>
		<option enabled="yes"><![CDATA[LMST(S)]]></option>
		<option enabled="yes"><![CDATA[LMST(D)]]></option>
		<option enabled="no"><![CDATA[DVB-S]]></option>
		<option enabled="no"><![CDATA[DVB-S2]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_L2174_FREQ1</name>
		<display><![CDATA[Frequency]]></display>
		<units type="sym">GHz</units>
		<min>0.070</min>
		<max>10.00</max>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_MOD_TYPE</name>
		<display><![CDATA[Mode]]></display>
		<option enabled="yes"><![CDATA[QPSK]]></option>
		<option enabled="yes"><![CDATA[16QAM]]></option>
		<option enabled="yes"><![CDATA[64QAM]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_L2174_CHAN_BW</name>
		<display><![CDATA[Bandwidth]]></display>
		<option enabled="yes"><![CDATA[3MHz]]></option>
		<option enabled="yes"><![CDATA[4MHz]]></option>
		<option enabled="yes"><![CDATA[5MHz]]></option>
		<option enabled="yes"><![CDATA[6MHz]]></option>
		<option enabled="yes"><![CDATA[7MHz]]></option>
		<option enabled="yes"><![CDATA[8MHz]]></option>
		<option enabled="yes"><![CDATA[10MHz]]></option>
		<option enabled="yes"><![CDATA[12MHz]]></option>
		<option enabled="no"><![CDATA[14MHz]]></option>
		<option enabled="no"><![CDATA[16MHz]]></option>
		<option enabled="no"><![CDATA[20MHz]]></option>
		<option enabled="no"><![CDATA[24MHz]]></option>
		<option enabled="no"><![CDATA[Auto]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_GUARD_INT</name>
		<display><![CDATA[Guard Interval]]></display>
		<option enabled="no"><![CDATA[1/32]]></option>
		<option enabled="yes"><![CDATA[1/16]]></option>
		<option enabled="yes"><![CDATA[1/8]]></option>
		<option enabled="no"><![CDATA[1/4]]></option>
		<option enabled="yes"><![CDATA[Auto]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_SPEC_POL</name>
		<display><![CDATA[Polarity]]></display>
		<option enabled="yes"><![CDATA[Normal]]></option>
		<option enabled="yes"><![CDATA[Inverted]]></option>
		<option enabled="no"><![CDATA[Auto]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_FEC_RATE</name>
		<display><![CDATA[FEC Rate]]></display>
		<option enabled="yes"><![CDATA[1/2]]></option>
		<option enabled="yes"><![CDATA[2/3]]></option>
		<option enabled="yes"><![CDATA[3/4]]></option>
		<option enabled="yes"><![CDATA[5/6]]></option>
		<option enabled="yes"><![CDATA[7/8]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_PRE_BER</name>
		<display><![CDATA[Pre-BER]]></display>
		<units type="sym"> e-6</units>
		<min>0</min>
		<max>4294967295</max>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_POST_BER</name>
		<display><![CDATA[Post-BER]]></display>
		<units type="sym"> e-6</units>
		<min>0</min>
		<max>4294967295</max>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_TPS_LOCK</name>
		<display><![CDATA[TPS Lock]]></display>
		<option enabled="yes"><![CDATA[No Lock]]></option>
		<option enabled="yes"><![CDATA[Locked]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_FEC_LOCK</name>
		<display><![CDATA[FEC Lock]]></display>
		<option enabled="yes"><![CDATA[No Lock]]></option>
		<option enabled="yes"><![CDATA[Locked]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_PKT_ERR_RATE</name>
		<display><![CDATA[Packet Errors]]></display>
		<units type="sym"></units>
		<min>0</min>
		<max>4294967295</max>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_RX_MODE</name>
		<display><![CDATA[Mode]]></display>
		<option enabled="yes"><![CDATA[LMST(S)]]></option>
		<option enabled="yes"><![CDATA[DVB-T]]></option>
		<option enabled="yes"><![CDATA[LMST(D)]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_SOURCE_ID</name>
		<display><![CDATA[Decoder ID]]></display>
	</parameter>
	<parameter visible="yes">
		<name>DB_ETRAX_SOURCE_ID</name>
		<display><![CDATA[Control ID]]></display>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_SPEC_POL</name>
		<display><![CDATA[Polarity demod]]></display>
		<option enabled="yes"><![CDATA[Normal]]></option>
		<option enabled="yes"><![CDATA[Inverted]]></option>
		<option enabled="no"><![CDATA[Auto]]></option>
	</parameter>
	<parameter visible="no">
		<name>DB_P17101_LO_MIX</name>
		<display><![CDATA[LO mix]]></display>
		<option enabled="yes"><![CDATA[Low side]]></option>
		<option enabled="yes"><![CDATA[High side]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_ASI1_OUTPUT_MUX</name>
		<display><![CDATA[Demod Output 1]]></display>
		<option enabled="yes"><![CDATA[Demod]]></option>
		<option enabled="yes"><![CDATA[Ext ASI]]></option>
		<option enabled="no"><![CDATA[Diversity]]></option>
		<option enabled="no"><![CDATA[Off]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_ASI2_OUTPUT_MUX</name>
		<display><![CDATA[Demod Output 2]]></display>
		<option enabled="yes"><![CDATA[Demod]]></option>
		<option enabled="yes"><![CDATA[Ext ASI]]></option>
		<option enabled="no"><![CDATA[Diversity]]></option>
		<option enabled="no"><![CDATA[Off]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_VIDEO_OUTPUT_MUX</name>
		<display><![CDATA[Decoder Source]]></display>
		<option enabled="yes"><![CDATA[Demod out 1]]></option>
		<option enabled="yes"><![CDATA[Demod out 2]]></option>
		<option enabled="no"><![CDATA[Demodulator]]></option>
		<option enabled="no"><![CDATA[Ext ASI]]></option>
		<option enabled="yes"><![CDATA[IP]]></option>
		<option enabled="no"><![CDATA[Descrambler]]></option>
		<option enabled="no"><![CDATA[Off]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_ASI_OUTPUT_MUX</name>
		<display><![CDATA[ASI Out Source]]></display>
		<option enabled="yes"><![CDATA[Demod out 1]]></option>
		<option enabled="yes"><![CDATA[Demod out 2]]></option>
		<option enabled="no"><![CDATA[3 Demodulator]]></option>
		<option enabled="no"><![CDATA[4 Ext ASI]]></option>
		<option enabled="yes"><![CDATA[IP]]></option>
		<option enabled="no"><![CDATA[Descrambler]]></option>
		<option enabled="no"><![CDATA[Off]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_IP1_OUTPUT_MUX</name>
		<display><![CDATA[IP Out Source]]></display>
		<option enabled="yes"><![CDATA[Demod out 1]]></option>
		<option enabled="yes"><![CDATA[Demod out 2]]></option>
		<option enabled="no"><![CDATA[Demodulator]]></option>
		<option enabled="no"><![CDATA[Ext ASI]]></option>
		<option enabled="no"><![CDATA[IP]]></option>
		<option enabled="no"><![CDATA[Descrambler]]></option>
		<option enabled="yes"><![CDATA[Off]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_L2174_DOWN_CONVERTER_1</name>
		<display><![CDATA[Downconverter]]></display>
		<option enabled="yes"><![CDATA[L3010Lo]]></option>
		<option enabled="yes"><![CDATA[L3010Hi]]></option>
		<option enabled="yes"><![CDATA[L3014]]></option>
		<option enabled="yes"><![CDATA[L3030]]></option>
		<option enabled="yes"><![CDATA[L3033]]></option>
		<option enabled="yes"><![CDATA[L3034]]></option>
		<option enabled="yes"><![CDATA[L3037]]></option>
		<option enabled="yes"><![CDATA[L3039]]></option>
		<option enabled="yes"><![CDATA[L3060]]></option>
		<option enabled="yes"><![CDATA[L3066]]></option>
		<option enabled="yes"><![CDATA[L3080]]></option>
		<option enabled="yes"><![CDATA[L3085]]></option>
		<option enabled="yes"><![CDATA[L3090]]></option>
		<option enabled="yes"><![CDATA[L9234]]></option>
		<option enabled="yes"><![CDATA[L3025-1415]]></option>
		<option enabled="yes"><![CDATA[L3025-1718]]></option>
		<option enabled="yes"><![CDATA[L3025-1927]]></option>
		<option enabled="yes"><![CDATA[3025-1927E]]></option>
		<option enabled="yes"><![CDATA[L3025-2024]]></option>
		<option enabled="yes"><![CDATA[L3025-2732]]></option>
		<option enabled="yes"><![CDATA[L3025-3236]]></option>
		<option enabled="yes"><![CDATA[3025-3239E]]></option>
		<option enabled="yes"><![CDATA[L3025-4450]]></option>
		<option enabled="yes"><![CDATA[L3025-5459]]></option>
		<option enabled="yes"><![CDATA[L3025-6471]]></option>
		<option enabled="yes"><![CDATA[L3025-6875]]></option>
		<option enabled="yes"><![CDATA[L3025-7277]]></option>
		<option enabled="yes"><![CDATA[L3025-6368]]></option>
		<option enabled="yes"><![CDATA[Other]]></option>
		<option enabled="yes"><![CDATA[None]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="no">
		<name>DB_L2174_OTHER_LO_1</name>
		<display><![CDATA[Other LO Frequency]]></display>
		<units type="sym">GHz</units>
		<min>0.070</min>
		<max>10.00</max>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_LNB_PWR_1</name>
		<display><![CDATA[Downconverter 1 Power]]></display>
		<option enabled="yes"><![CDATA[Off]]></option>
		<option enabled="yes"><![CDATA[On]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_LNB_PWR_2</name>
		<display><![CDATA[Downconverter 2 Power]]></display>
		<option enabled="yes"><![CDATA[Off]]></option>
		<option enabled="yes"><![CDATA[On]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_LNB_PWR_3</name>
		<display><![CDATA[Downconverter 3 Power]]></display>
		<option enabled="yes"><![CDATA[Off]]></option>
		<option enabled="yes"><![CDATA[On]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_LNB_PWR_4</name>
		<display><![CDATA[Downconverter 4 Power]]></display>
		<option enabled="yes"><![CDATA[Off]]></option>
		<option enabled="yes"><![CDATA[On]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_PWR_LEVEL_1</name>
		<display><![CDATA[Input 1 Power level]]></display>
		<units type="sym">dB</units>
		<min>-150</min>
		<max>10</max>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_PWR_LEVEL_2</name>
		<display><![CDATA[Input 2 Power level]]></display>
		<units type="sym">dB</units>
		<min>-150</min>
		<max>10</max>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_PWR_LEVEL_3</name>
		<display><![CDATA[Input 3 Power level]]></display>
		<units type="sym">dB</units>
		<min>-150</min>
		<max>10</max>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_PWR_LEVEL_4</name>
		<display><![CDATA[Input 4 Power level]]></display>
		<units type="sym">dB</units>
		<min>-150</min>
		<max>10</max>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_MER_1</name>
		<display><![CDATA[Input 1 MER]]></display>
		<units type="sym">dB</units>
		<min>-10</min>
		<max>40</max>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_MER_2</name>
		<display><![CDATA[Input 2 MER]]></display>
		<units type="sym">dB</units>
		<min>-10</min>
		<max>40</max>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_MER_3</name>
		<display><![CDATA[Input 3 MER]]></display>
		<units type="sym">dB</units>
		<min>-10</min>
		<max>40</max>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_MER_4</name>
		<display><![CDATA[Input 4 MER]]></display>
		<units type="sym">dB</units>
		<min>-10</min>
		<max>40</max>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_COARSE_LOCK_1</name>
		<display><![CDATA[Channel 1 Lock]]></display>
		<option enabled="yes"><![CDATA[No Lock]]></option>
		<option enabled="yes"><![CDATA[Locked]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_COARSE_LOCK_2</name>
		<display><![CDATA[Channel 2 Lock]]></display>
		<option enabled="yes"><![CDATA[No Lock]]></option>
		<option enabled="yes"><![CDATA[Locked]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_COARSE_LOCK_3</name>
		<display><![CDATA[Channel 3 Lock]]></display>
		<option enabled="yes"><![CDATA[No Lock]]></option>
		<option enabled="yes"><![CDATA[Locked]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DEMOD_COARSE_LOCK_4</name>
		<display><![CDATA[Channel 4 Lock]]></display>
		<option enabled="yes"><![CDATA[No Lock]]></option>
		<option enabled="yes"><![CDATA[Locked]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_DATA_ENABLE</name>
		<display><![CDATA[Data]]></display>
		<option enabled="yes"><![CDATA[Off]]></option>
		<option enabled="yes"><![CDATA[On]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_DATA_BAUD</name>
		<display><![CDATA[Data Rate]]></display>
		<option enabled="yes"><![CDATA[300]]></option>
		<option enabled="yes"><![CDATA[600]]></option>
		<option enabled="yes"><![CDATA[1200]]></option>
		<option enabled="yes"><![CDATA[2400]]></option>
		<option enabled="yes"><![CDATA[4800]]></option>
		<option enabled="yes"><![CDATA[9600]]></option>
		<option enabled="yes"><![CDATA[19200]]></option>
		<option enabled="yes"><![CDATA[38400]]></option>
		<option enabled="yes"><![CDATA[57600]]></option>
		<option enabled="yes"><![CDATA[115200]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_DATA_PARITY</name>
		<display><![CDATA[Data Parity]]></display>
		<option enabled="yes"><![CDATA[Odd]]></option>
		<option enabled="yes"><![CDATA[Even]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_AUTO_SERVICE</name>
		<display><![CDATA[Auto Service Enabled]]></display>
		<option enabled="yes"><![CDATA[Off]]></option>
		<option enabled="yes"><![CDATA[On]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_NUM_SERVICES</name>
		<display><![CDATA[No. of Services]]></display>
		<units type="sym"></units>
		<min>0</min>
		<max>99</max>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_SERVICE_NAME</name>
		<display><![CDATA[Default Service Name]]></display>
	</parameter>
	<parameter visible="yes">
		<name>DB_L2174_SERVICE_NAME_LIST</name>
		<display><![CDATA[Current Service Name]]></display>
		<option enabled="yes"><![CDATA[No Service]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_PCR_LOCK</name>
		<display><![CDATA[PCR Lock]]></display>
		<option enabled="yes"><![CDATA[No Lock]]></option>
		<option enabled="yes"><![CDATA[Locked]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_GEN_LOCK_ERROR</name>
		<display><![CDATA[Frame Lock Error]]></display>
		<option enabled="yes"><![CDATA[OK]]></option>
		<option enabled="yes"><![CDATA[Fail]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_NETWORK_NAME</name>
		<display><![CDATA[Network Name]]></display>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_CHROMA</name>
		<display><![CDATA[Chroma]]></display>
		<option enabled="yes"><![CDATA[4:2:0]]></option>
		<option enabled="yes"><![CDATA[4:2:2]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_FREEZE_ON_LOSS</name>
		<display><![CDATA[Freeze on Loss]]></display>
		<option enabled="yes"><![CDATA[Freeze]]></option>
		<option enabled="yes"><![CDATA[Blue]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_PSF_MODE</name>
		<display><![CDATA[PSF Mode]]></display>
		<option enabled="yes"><![CDATA[Off]]></option>
		<option enabled="yes"><![CDATA[On]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_L2174_VIDEO_INPUT_MODE</name>
		<display><![CDATA[Video Input Mode]]></display>
		<option enabled="no"><![CDATA[Off]]></option>
		<option enabled="no"><![CDATA[Auto]]></option>
		<option enabled="yes"><![CDATA[SD MPEG2 LD]]></option>
		<option enabled="yes"><![CDATA[HD MPEG2 LD]]></option>
		<option enabled="yes"><![CDATA[H264]]></option>
		<option enabled="yes"><![CDATA[MPEG2]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_LINE_STD</name>
		<display><![CDATA[Detected Video Mode]]></display>
		<option enabled="yes"><![CDATA[625]]></option>
		<option enabled="yes"><![CDATA[525]]></option>
		<option enabled="yes"><![CDATA[720P/50]]></option>
		<option enabled="yes"><![CDATA[720P/59]]></option>
		<option enabled="yes"><![CDATA[720P/60]]></option>
		<option enabled="yes"><![CDATA[1080I/50]]></option>
		<option enabled="yes"><![CDATA[1080I/59]]></option>
		<option enabled="yes"><![CDATA[1080I/60]]></option>
		<option enabled="yes"><![CDATA[1080P/23]]></option>
		<option enabled="yes"><![CDATA[1080P/24]]></option>
		<option enabled="yes"><![CDATA[1080P/25]]></option>
		<option enabled="yes"><![CDATA[1080P/29]]></option>
		<option enabled="yes"><![CDATA[1080P/30]]></option>
		<option enabled="yes"><![CDATA[1080PsF23]]></option>
		<option enabled="yes"><![CDATA[1080PsF24]]></option>
		<option enabled="yes"><![CDATA[1080PsF25]]></option>
		<option enabled="yes"><![CDATA[1080PsF29]]></option>
		<option enabled="yes"><![CDATA[1080PsF30]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_VIDEO_A_TYPE</name>
		<display><![CDATA[Video Output 1 Format]]></display>
		<option enabled="yes"><![CDATA[SDI]]></option>
		<option enabled="no"><![CDATA[SDI+Overlay]]></option>
		<option enabled="no"><![CDATA[Composite]]></option>
		<option enabled="no"><![CDATA[Comp+Overlay]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="yes">
		<name>DB_DECOD_VIDEO_B_TYPE</name>
		<display><![CDATA[Video Output 2 Format]]></display>
		<option enabled="yes"><![CDATA[SDI]]></option>
		<option enabled="no"><![CDATA[SDI+Overlay]]></option>
		<option enabled="yes"><![CDATA[Composite]]></option>
		<option enabled="no"><![CDATA[Comp+Overlay]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="no">
		<name>DB_L2174_MPEG1_AUDIO_A_BITRATE</name>
		<display><![CDATA[Audio 1 Bitrate]]></display>
		<option enabled="no"><![CDATA[]]></option>
		<option enabled="yes"><![CDATA[32Kbs]]></option>
		<option enabled="yes"><![CDATA[64Kbs]]></option>
		<option enabled="yes"><![CDATA[96Kbs]]></option>
		<option enabled="yes"><![CDATA[128Kbs]]></option>
		<option enabled="yes"><![CDATA[160Kbs]]></option>
		<option enabled="yes"><![CDATA[192Kbs]]></option>
		<option enabled="yes"><![CDATA[224Kbs]]></option>
		<option enabled="yes"><![CDATA[256Kbs]]></option>
		<option enabled="yes"><![CDATA[288Kbs]]></option>
		<option enabled="yes"><![CDATA[320Kbs]]></option>
		<option enabled="yes"><![CDATA[352Kbs]]></option>
		<option enabled="yes"><![CDATA[384Kbs]]></option>
		<option enabled="yes"><![CDATA[416Kbs]]></option>
		<option enabled="yes"><![CDATA[448Kbs]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="no">
		<name>DB_L2174_MPEG2_AUDIO_A_BITRATE</name>
		<display><![CDATA[Audio 1 Bitrate]]></display>
		<option enabled="no"><![CDATA[]]></option>
		<option enabled="yes"><![CDATA[32Kbs]]></option>
		<option enabled="yes"><![CDATA[48Kbs]]></option>
		<option enabled="yes"><![CDATA[56Kbs]]></option>
		<option enabled="yes"><![CDATA[64Kbs]]></option>
		<option enabled="yes"><![CDATA[80Kbs]]></option>
		<option enabled="yes"><![CDATA[96Kbs]]></option>
		<option enabled="yes"><![CDATA[112Kbs]]></option>
		<option enabled="yes"><![CDATA[128Kbs]]></option>
		<option enabled="yes"><![CDATA[160Kbs]]></option>
		<option enabled="yes"><![CDATA[192Kbs]]></option>
		<option enabled="yes"><![CDATA[224Kbs]]></option>
		<option enabled="yes"><![CDATA[256Kbs]]></option>
		<option enabled="yes"><![CDATA[320Kbs]]></option>
		<option enabled="yes"><![CDATA[384Kbs]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="no">
		<name>DB_L2174_MPEG1_AUDIO_B_BITRATE</name>
		<display><![CDATA[Audio 2 Bitrate]]></display>
		<option enabled="no"><![CDATA[]]></option>
		<option enabled="yes"><![CDATA[32Kbs]]></option>
		<option enabled="yes"><![CDATA[64Kbs]]></option>
		<option enabled="yes"><![CDATA[96Kbs]]></option>
		<option enabled="yes"><![CDATA[128Kbs]]></option>
		<option enabled="yes"><![CDATA[160Kbs]]></option>
		<option enabled="yes"><![CDATA[192Kbs]]></option>
		<option enabled="yes"><![CDATA[224Kbs]]></option>
		<option enabled="yes"><![CDATA[256Kbs]]></option>
		<option enabled="yes"><![CDATA[288Kbs]]></option>
		<option enabled="yes"><![CDATA[320Kbs]]></option>
		<option enabled="yes"><![CDATA[352Kbs]]></option>
		<option enabled="yes"><![CDATA[384Kbs]]></option>
		<option enabled="yes"><![CDATA[416Kbs]]></option>
		<option enabled="yes"><![CDATA[448Kbs]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="no">
		<name>DB_L2174_MPEG2_AUDIO_B_BITRATE</name>
		<display><![CDATA[Audio 2 Bitrate]]></display>
		<option enabled="no"><![CDATA[]]></option>
		<option enabled="yes"><![CDATA[32Kbs]]></option>
		<option enabled="yes"><![CDATA[48Kbs]]></option>
		<option enabled="yes"><![CDATA[56Kbs]]></option>
		<option enabled="yes"><![CDATA[64Kbs]]></option>
		<option enabled="yes"><![CDATA[80Kbs]]></option>
		<option enabled="yes"><![CDATA[96Kbs]]></option>
		<option enabled="yes"><![CDATA[112Kbs]]></option>
		<option enabled="yes"><![CDATA[128Kbs]]></option>
		<option enabled="yes"><![CDATA[160Kbs]]></option>
		<option enabled="yes"><![CDATA[192Kbs]]></option>
		<option enabled="yes"><![CDATA[224Kbs]]></option>
		<option enabled="yes"><![CDATA[256Kbs]]></option>
		<option enabled="yes"><![CDATA[320Kbs]]></option>
		<option enabled="yes"><![CDATA[384Kbs]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="no">
		<name>DB_L2174_MPEG1_AUDIO_C_BITRATE</name>
		<display><![CDATA[Audio 3 Bitrate]]></display>
		<option enabled="no"><![CDATA[]]></option>
		<option enabled="yes"><![CDATA[32Kbs]]></option>
		<option enabled="yes"><![CDATA[64Kbs]]></option>
		<option enabled="yes"><![CDATA[96Kbs]]></option>
		<option enabled="yes"><![CDATA[128Kbs]]></option>
		<option enabled="yes"><![CDATA[160Kbs]]></option>
		<option enabled="yes"><![CDATA[192Kbs]]></option>
		<option enabled="yes"><![CDATA[224Kbs]]></option>
		<option enabled="yes"><![CDATA[256Kbs]]></option>
		<option enabled="yes"><![CDATA[288Kbs]]></option>
		<option enabled="yes"><![CDATA[320Kbs]]></option>
		<option enabled="yes"><![CDATA[352Kbs]]></option>
		<option enabled="yes"><![CDATA[384Kbs]]></option>
		<option enabled="yes"><![CDATA[416Kbs]]></option>
		<option enabled="yes"><![CDATA[448Kbs]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="no">
		<name>DB_L2174_MPEG2_AUDIO_C_BITRATE</name>
		<display><![CDATA[Audio 3 Bitrate]]></display>
		<option enabled="no"><![CDATA[]]></option>
		<option enabled="yes"><![CDATA[32Kbs]]></option>
		<option enabled="yes"><![CDATA[48Kbs]]></option>
		<option enabled="yes"><![CDATA[56Kbs]]></option>
		<option enabled="yes"><![CDATA[64Kbs]]></option>
		<option enabled="yes"><![CDATA[80Kbs]]></option>
		<option enabled="yes"><![CDATA[96Kbs]]></option>
		<option enabled="yes"><![CDATA[112Kbs]]></option>
		<option enabled="yes"><![CDATA[128Kbs]]></option>
		<option enabled="yes"><![CDATA[160Kbs]]></option>
		<option enabled="yes"><![CDATA[192Kbs]]></option>
		<option enabled="yes"><![CDATA[224Kbs]]></option>
		<option enabled="yes"><![CDATA[256Kbs]]></option>
		<option enabled="yes"><![CDATA[320Kbs]]></option>
		<option enabled="yes"><![CDATA[384Kbs]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="no">
		<name>DB_L2174_MPEG1_AUDIO_D_BITRATE</name>
		<display><![CDATA[Audio 4 Bitrate]]></display>
		<option enabled="no"><![CDATA[]]></option>
		<option enabled="yes"><![CDATA[32Kbs]]></option>
		<option enabled="yes"><![CDATA[64Kbs]]></option>
		<option enabled="yes"><![CDATA[96Kbs]]></option>
		<option enabled="yes"><![CDATA[128Kbs]]></option>
		<option enabled="yes"><![CDATA[160Kbs]]></option>
		<option enabled="yes"><![CDATA[192Kbs]]></option>
		<option enabled="yes"><![CDATA[224Kbs]]></option>
		<option enabled="yes"><![CDATA[256Kbs]]></option>
		<option enabled="yes"><![CDATA[288Kbs]]></option>
		<option enabled="yes"><![CDATA[320Kbs]]></option>
		<option enabled="yes"><![CDATA[352Kbs]]></option>
		<option enabled="yes"><![CDATA[384Kbs]]></option>
		<option enabled="yes"><![CDATA[416Kbs]]></option>
		<option enabled="yes"><![CDATA[448Kbs]]></option>
		<option enabled="no"><![CDATA[---]]></option>
	</parameter>
	<parameter visible="no">
		<name>DB_L2174_MPEG2_AUDIO_D_BITRATE</name>
		<display><![CDATA[Audio 4 Bitrate]]></display>